version: '3'
services:
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ux-analyzer-api
    tty: true
    environment:
      SERVICE_NAME: ux-analyzer-api
      SERVICE_TAGS: dev
      DB_NAME: ux-analyzer
      DB_USER: ux-analyzer
      DB_PASS: ux-analyzer
      DB_HOST: ux-analyzer-db
    ports:
      - "8002:8000"
    volumes:
      - ./src:/usr/src/app/ux-analyzer-api/src
  db:
    image: mariadb:11.0
    container_name: ux-analyzer-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ux-analyzer
      MYSQL_ROOT_PASSWORD: ux-analyzer
      MYSQL_USER: ux-analyzer
      MYSQL_PASSWORD: ux-analyzer
      SERVICE_TAGS: dev
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local