# Generated by Django 4.1.5 on 2023-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(default='no-id', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
