# Generated by Django 4.1.5 on 2023-01-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_evaluation_version_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='urls',
            field=models.CharField(default='no-url', max_length=500),
            preserve_default=False,
        ),
    ]
