# Generated by Django 4.1.5 on 2023-10-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_evaluation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetlog',
            name='widget_label',
        ),
        migrations.RemoveField(
            model_name='widgetlog',
            name='widget_type',
        ),
        migrations.RemoveField(
            model_name='widgetlog',
            name='widget_url',
        ),
        migrations.RemoveField(
            model_name='widgetlog',
            name='widget_xpath',
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('xpath', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('TextInput', 'TextInput'), ('SelectInput', 'SelectInput'), ('Anchor', 'Anchor'), ('Datepicker', 'Datepicker'), ('DateSelect', 'DateSelect'), ('RadioSet', 'RadioSet')], max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('weight', models.IntegerField(default=1)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='evaluations.version')),
            ],
        ),
        migrations.AddField(
            model_name='widgetlog',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='evaluations.widget'),
        ),
    ]
