# Generated by Django 4.1.5 on 2023-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_remove_widgetlog_widget_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
