# Generated by Django 4.1.5 on 2024-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_alter_widget_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetlog',
            name='interaction_effort',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
