# Generated by Django 4.1.5 on 2024-11-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_widgetlog_interaction_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetlog',
            name='interaction_effort',
            field=models.FloatField(null=True),
        ),
    ]
