# Generated by Django 4.1.5 on 2024-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_alter_widgetlog_interaction_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
